# Generated by Django 5.2 on 2025-05-09 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('repository', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/')),
                ('skills', models.ManyToManyField(related_name='projects', to='projects.skill')),
            ],
        ),
    ]
