# Generated by Django 5.2 on 2025-05-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('duration', models.CharField(help_text='Format: Month YYYY - Month YYYY or Month YYYY - Present', max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
